Added U4U Slack module
USAFORUNHCRhive/u4u_util pull request #3
Opened 2024-08-08 17:02 UTC by anderoos

2024-08-08 17:40 UTC, ktnharris22 requested changes
Did you test this within the USA for UNHCR slack already?

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/base.py
> +    def message_edit(self, channel: str, ts: str, text: str) -> None:
I don't know if we have a use case for this.

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/base.py
> +    def message_append(self, channel: str, ts: str, text: str) -> None:
Also don't know if we have a use case for this.

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/config.py
Why is this a separate file and not just included in base.py?

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/base.py
> +    def message_delete(self, channel: str, ts: str) -> None:
Not sure what the use case is for this either.

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/base.py
> +    def file_post(self, channel: str, file: str, title: str, initial_comments: str) -> None:
This is cool! Idk if we have a use case right now but maybe in the future.

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/alerts.py
It would be easier to use if the send_slack_message function was implemented here.

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/slack_utilities/logging.py
Why is this a separate file? And not included in the base file?

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/base.py
> +        self.client = WebClient(token=SlackConfig.SLACK_TOKEN)
It would be good too to send an email alert here if the SLACK_TOKEN is expired or otherwise unusable.

2024-08-08 17:40 UTC, ktnharris22 commented on Utils/slack_alerts/tests/test_base.py
What tests were you thinking of here? Not a lot of logic to test.

2024-08-15 18:42 UTC, ktnharris22 requested changes

2024-08-15 18:42 UTC, ktnharris22 commented on Utils/alerts.py
> +    def message_post(self, text, channel: str = SLACK_CHANNEL, blocks: List[Dict[str, str]] = None) -> None:
Can you send a slack message to a single person like a DM or is only to channels? Also can we send to multiple channels with the same slack token/app?

2024-08-15 18:42 UTC, ktnharris22 commented on Utils/alerts.py
> +                Source="hive@u4u-email.com",
This is outdated... the u4u-email.com domain doesn't exist anymore. I was able to get us to be able to send an email from an [at]unrefugees[dot]org email so they now originate from the hive[at]unrefugees[dot]org.

See here for more details https://github.com/USAFORUNHCRhive/Integrations/blob/main/src/Salesforce/SESEmailer/emailer.py

2024-08-15 18:42 UTC, ktnharris22 commented on Utils/alerts.py
> +    SLACK_CHANNEL = os.getenv('SLACK_CHANNEL')
I think this probably should just be a parameter instead. No need for a env var unless we can only post one channel which I'm hoping is not the case.

2024-08-16 20:54 UTC, anderoos commented
As of 8/16/24, sending messages across multiple channels seems to work as intended. Our Slack API's scope needs to be updated to include private DM messages. I've left the code in here for future testing.

2024-11-13 21:54 UTC, ktnharris22 commented
Merging so we can move to new org here https://github.com/USA-for-UNHCR/U4U_Utils

2024-11-13 21:54 UTC, merged